### ISSUE TITLE
What is the meaning of "a,b" in trainer? 

### ISSUE THREAD

**Issue by jackie840129** [NVlabs/DG-Net#6]
Hi, in DGNet_Trainer, you have gen_a, gen_b. I'm confused that in a single dataset training, do you need two generators a and b?
What is the meaning of feeding image a and image b in your trainer?
Thanks!

**Comment by layumi** [comment]
Hi @jackie840129 

Thank you. Image a and Image b are two different samples from one dataset.

So we could use the same encoder/decoder/discriminator for image a and b (Since they are from the same dataset/domain). You may notice that I have written the following lines in the `trainer.py`. In fact, they are identical.

```python
self.gen_b = self.gen_a
self.id_b = self.id_a
self.dis_b = self.dis_a
```

**Comment by jackie840129** [comment]
Thank you for the quick reply!
I know the generators are the same, but why not just sample two times larger data?
(Because a and b are from the same dataset)

**Comment by layumi** [comment]
Hi @jackie840129 

Yes. Your suggestion is good. We, however, want to keep our code more easy to be modified. So we left the two dataloaders for one dataset. In this way, the code could be more easily adapted to the cross-dataset image generation, e.g., dog and cat, which needs two dataloaders.

**Comment by jackie840129** [comment]
Hi @layumi 
I see. Thank you very much for your quick reply!
